version: "3"

services:
  airsonic:
    container_name: airsonic-tft
    image: airsonicadvanced/airsonic-advanced:edge-latest
    user: root
    env_file:
      - .env
    volumes:
      - '/data/airsonic/:/data/airsonic/'
      - '/data/music:/data/music'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.rule=Host(`music.tft`)"
      - "traefik.http.routers.airsonic.entrypoints=websecure"
      - "traefik.http.routers.airsonic.tls=true"
      - "traefik.http.routers.airsonic.tls.certresolver=myresolver"
      - "traefik.http.routers.airsonic.service=airsonic"
      - "traefik.http.services.airsonic.loadbalancer.server.port=8888"
      - "traefik.http.middlewares.airsonic.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.airsonic.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.airsonic.headers.stsPreload=true"
      - "traefik.http.middlewares.airsonic.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.airsonic.headers.contentSecurityPolicy=frame-ancestors 'self' *.tft"
      - "traefik.http.middlewares.airsonic.headers.customFrameOptionsValue=SAMEORIGIN"
    networks:
      - internal

networks:
  internal:
    external:
      name: internal
