version: "3.3"

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
    image: "services/step-traefik-v2.2.8:1.0.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.caserver=https://ca.tft:8443/acme/acme/directory"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@thedukedk.net"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    labels:
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false"
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    environment:
      - LEGO_CA_CERTIFICATES=/root/.step/certs/root_ca.crt # This is where step installs the cert when the client is bootstrapped.
      - CERT_AUTH=${CERT_AUTH:-localhost}
      - CERT_AUTH_PORT=${CERT_AUTH_PORT:-8443}
      - CERT_AUTH_PROVISIONER=${CERT_AUTH_PROVISIONER:-acme}
      - FINGERPRINT=${FINGERPRINT}
    networks:
      - external
      - internal

networks:
  external:
    external:
      name: external
  internal:
    external:
      name: internal

