version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /data/uptimekarma/:/app/data
        #ports:
            #  - 8080:3001
    network_mode: host
    environment:
      - UPTIME_KUMA_PORT=8080
    restart: unless-stopped
