version: "3.4"

services:
  app:
    image: monica:apache
    depends_on:
      - db
    ports:
      - 3074:80
    environment:
      - APP_TRUSTED_PROXIES=*
      - DB_HOST=db
      - DB_USERNAME=changeme
      - DB_PASSWORD=changeme
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=monic
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
